# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

contact_links:
  - name: Ask a Question
    url: https://discuss.hashicorp.com/c/vagrant
    about: If you have a question or are looking for advice, please post on our Discuss forum.
