search:
  paths:
    - "bin/"
    - "lib/"
    - "plugins/"
  scanner: Vagrant::Util::I18nScanner
data:
  adapter: yaml
  read:
    - 'templates/locales/%{locale}.yml'
  write:
    - 'templates/locales/%{locale}.yml'
