name: Legacy Link Format Checker

on: [deployment_status]

jobs:
  check-links:
    if: github.event.deployment_status.state == 'success'
    uses: hashicorp/dev-portal/.github/workflows/docs-content-check-legacy-links-format.yml@d3c23a582bc0e02a62545644f1fb0a3922cc4b17
    with:
      repo-owner: "hashicorp"
      repo-name: "vagrant"
      commit-sha: ${{ github.sha }}
      mdx-directory: "website/content"
      nav-data-directory: "website/data"
