on:
  push:
    branches:
      - 'main'
      - 'spec-test-*'

jobs:
  sync-acceptance:
    if: github.repository == 'hashicorp/vagrant'
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sync Acceptance Testing Repository
        run: ./.ci/sync.sh
        working-directory: ${{github.workspace}}
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
