name: DEB Vagrant Development Build
on:
  push:
    branches: 'dev-debs-*'
  workflow_dispatch:

jobs:
  trigger-build:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Vagrant DEB Development Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Trigger Development Build
        run: ./.ci/dev-build "${BRANCH}" "${COMMIT_ID}" build-debs
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_ID: ${{ github.sha }}
