name: RPM Vagrant Development Build
on:
  push:
    branches: 'dev-rpms-*'
  workflow_dispatch:

jobs:
  trigger-build:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Vagrant RPM Development Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Trigger Development Build
        run: ./.ci/dev-build "${BRANCH}" "${COMMIT_ID}" build-rpms
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_ID: ${{ github.sha }}
