name: Arch Linux Vagrant Development Build
on:
  push:
    branches: 'dev-arch-*'
  workflow_dispatch:

jobs:
  trigger-build:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Vagrant Arch Linux Development Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Trigger Development Build
        run: ./.ci/dev-build "${BRANCH}" "${COMMIT_ID}" build-arch
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_ID: ${{ github.sha }}
