name: Start Vagrant Release Process
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version (example: 1.0.0)'
        required: true
        type: string

jobs:
  start-release:
    if: github.repository == 'hashicorp/vagrant'
    name: Initiate Release
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          # NOTE: custom token is used so pushed tag will trigger release workflow
          token: ${{ secrets.HASHIBOT_TOKEN }}
      - name: Run initiator
        run: ./.ci/release-initiator "${VERSION}"
        env:
          VERSION: ${{ inputs.release_version }}
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ vars.HASHIBOT_USERNAME }}
          HASHIBOT_EMAIL: ${{ vars.HASHIBOT_EMAIL }}
