name: Vagrant Nightly Builds
on:
  schedule:
    - cron: 30 4 * * *

jobs:
  trigger-nightly:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Nightly Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Trigger Nightly Build
        run: ./.ci/nightly-build "${COMMIT_ID}"
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          COMMIT_ID: ${{ github.sha }}
